export interface Perfil{
    fotoPerfil?:any,
    nomePerfil:string,
    frasePerfil?:string,
    genero?:string,
    estado?:string,
    cidade?:string,
    relacionamento?:string,
    aniversario?:string,
    quemSouEu?:string,
    livros?:string,
    musicas?:string,
    filmes?:string,
    created_at?:string,
    updated_at?:string,
}